"""
Solutions - Medium Quiz (Week 7: nuScenes 데이터셋)
"""


def main():
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("Week 7 Quiz - Medium 정답")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

    print("Q1. 좌표계 변환 (Global -> Ego):")
    print("    Step 1: ego_pose에서 Ego Vehicle의 위치(translation)와")
    print("            회전(rotation)을 가져온다.")
    print("            ego_translation = ego_pose['translation']")
    print("            ego_rotation = Quaternion(ego_pose['rotation'])")
    print()
    print("    Step 2: Global 좌표에서 Ego 위치를 빼서 상대 위치를 구한다.")
    print("            relative_pos = global_pos - ego_translation")
    print()
    print("    Step 3: Ego 회전의 역변환을 적용하여 Ego 좌표계로 변환한다.")
    print("            ego_pos = ego_rotation.inverse.rotate(relative_pos)")
    print()
    print("    Ego -> 카메라 좌표계 추가 변환:")
    print("    calibrated_sensor 테이블에서 해당 카메라의:")
    print("    - translation: Ego에서 카메라까지의 위치 오프셋")
    print("    - rotation: Ego에서 카메라까지의 회전")
    print("    - camera_intrinsic: 카메라 내부 파라미터 (K 행렬)")
    print("    이 세 가지 정보가 추가로 필요합니다.\n")

    print("Q2. Multi-camera 도전 과제:")
    print("    도전 과제 1: 카메라 겹침(overlap) 영역에서 중복 검출")
    print("      - 인접 카메라의 FOV가 겹치는 영역에서 같은 객체를")
    print("        두 번 검출할 수 있음")
    print("      해결 방법: BEV 공간에서 NMS 적용, 또는 Multi-view")
    print("      모델에서 통합적으로 처리 (BEVFormer 등)")
    print()
    print("    도전 과제 2: 후방 카메라(CAM_BACK)의 넓은 화각과 왜곡")
    print("      - 후방 카메라는 110도 화각으로 왜곡이 더 심하고,")
    print("        객체가 더 작게 보여 검출이 어려움")
    print("      해결 방법: 카메라별 별도 Feature 추출, 왜곡 보정,")
    print("      또는 카메라별 적응적 학습")
    print()
    print("    도전 과제 3: 시점 간 3D 일관성 유지")
    print("      - 여러 카메라의 예측 결과가 3D 공간에서 일관되어야 함")
    print("      - 각 카메라별 독립 예측은 일관성이 떨어질 수 있음")
    print("      해결 방법: BEV 표현으로 통합 (Lift-Splat-Shoot,")
    print("      BEVFormer), 또는 3D Query 기반 방법 (DETR3D)\n")

    print("Q3. Quaternion 회전 표현:")
    print("    1) Quaternion의 장점:")
    print("       - Gimbal Lock 없음: Euler 각도에서는 두 축이 겹칠 때")
    print("         자유도를 잃는 Gimbal Lock이 발생하지만,")
    print("         Quaternion은 이 문제가 없음")
    print("       - 부드러운 보간: SLERP(Spherical Linear Interpolation)으로")
    print("         두 회전 사이를 자연스럽게 보간 가능")
    print("       - 연산 효율: 회전 합성이 곱셈 한 번으로 가능 (4차원)")
    print("       - 수치 안정성: 정규화만 하면 유효한 회전을 보장")
    print()
    print("    2) q = [1, 0, 0, 0]: 회전 없음 (단위 Quaternion)")
    print("       항등 회전(identity rotation)을 나타냄")
    print()
    print("    3) 90도 yaw 회전 (z축 기준):")
    print("       theta = 90도 = pi/2 라디안")
    print("       q = [cos(pi/4), 0, 0, sin(pi/4)]")
    print("       q = [0.707, 0, 0, 0.707]")
    print("       (nuScenes의 z축이 위쪽이므로 z 성분에 sin 값)")

    print("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")


if __name__ == "__main__":
    main()
