"""
Phase 6 Week 11 - 코드 및 문서 정리 기초 퀴즈 정답 및 해설
"""


def problem1_solution():
    print("\n" + "━" * 28)
    print("문제 1 정답: C) 개발 일지와 일일 작업 로그")
    print("━" * 28 + "\n")

    print("해설:")
    print("  README에 반드시 포함해야 할 요소:")
    print("    1. 프로젝트 설명과 결과 이미지 (시각적 임팩트)")
    print("    2. 설치 방법과 실행 예시 (재현 가능성)")
    print("    3. 사용한 방법론과 참고 논문 (기술적 깊이)")
    print()
    print("  포함하지 않아도 되는 것:")
    print("    - 개발 일지, 일일 작업 로그")
    print("    → 이는 별도 문서(docs/)나 블로그에 기록")
    print("    → README는 '최종 결과'를 보여주는 곳")
    print()
    print("  README의 목적:")
    print("  면접관이 5분 안에 프로젝트를 이해할 수 있도록")
    print("  핵심 정보만 간결하게 전달하는 것입니다.")


def problem2_solution():
    print("\n" + "━" * 28)
    print("문제 2 정답: C) 대용량 데이터 파일")
    print("━" * 28 + "\n")

    print("해설:")
    print("  Git에 포함하면 안 되는 파일:")
    print("    - 대용량 데이터 파일 (.png, .pkl, .pth)")
    print("    - 모델 가중치 (수백 MB)")
    print("    - 환경 설정 (.env, 비밀키)")
    print("    - 캐시/빌드 파일 (__pycache__, .egg-info)")
    print()
    print("  Git에 포함해야 하는 파일:")
    print("    - requirements.txt (의존성 관리)")
    print("    - 소스 코드 (.py)")
    print("    - README.md (프로젝트 설명)")
    print("    - .gitignore (무시 규칙)")
    print("    - 설정 파일 (configs/)")
    print()
    print("  .gitignore에 추가할 패턴:")
    print("    data/")
    print("    *.pkl")
    print("    *.pth")
    print("    __pycache__/")
    print("    .DS_Store")


def problem3_solution():
    print("\n" + "━" * 28)
    print("문제 3 정답: B) Args, Returns, Examples")
    print("━" * 28 + "\n")

    print("해설:")
    print("  좋은 Docstring의 구성:")
    print()
    print("  1. 함수 설명 (첫 줄, 한 문장)")
    print("     → 이 함수가 무엇을 하는지")
    print()
    print("  2. Args (인자 설명)")
    print("     → 각 인자의 타입, 의미, shape")
    print()
    print("  3. Returns (반환값 설명)")
    print("     → 반환 타입, 의미, shape")
    print()
    print("  4. Examples (사용 예시, 선택)")
    print("     → 간단한 호출 예시와 기대 결과")
    print()
    print("  5. Raises (예외, 필요 시)")
    print("     → 발생할 수 있는 예외와 조건")
    print()
    print("  Google 스타일 예시:")
    print('    def add(a: int, b: int) -> int:')
    print('        """두 정수의 합을 반환한다.')
    print()
    print('        Args:')
    print('            a: 첫 번째 정수.')
    print('            b: 두 번째 정수.')
    print()
    print('        Returns:')
    print('            두 정수의 합.')
    print('        """')


def problem4_solution():
    print("\n" + "━" * 28)
    print("문제 4 정답: C) feat(visualization): ...")
    print("━" * 28 + "\n")

    print("해설:")
    print("  좋은 커밋 메시지의 조건:")
    print("    1. 무엇을 했는지 명확히 알 수 있어야 함")
    print("    2. type(scope) 형식으로 분류")
    print("    3. 간결하되 구체적")
    print()
    print("  각 보기 분석:")
    print("    A) 'update'")
    print("       → 무엇을 업데이트했는지 알 수 없음")
    print()
    print("    B) 'fix bug'")
    print("       → 어떤 버그인지 알 수 없음")
    print()
    print("    C) 'feat(visualization): 3D bbox BEV 시각화 함수 추가'")
    print("       → type: feat (새 기능)")
    print("       → scope: visualization (시각화 모듈)")
    print("       → subject: 구체적인 변경 내용")
    print("       → 가장 좋은 커밋 메시지!")
    print()
    print("    D) '2024-01-15 작업'")
    print("       → 날짜만으로는 내용을 알 수 없음")
    print()
    print("  Conventional Commits 규칙:")
    print("    feat: 새 기능  |  fix: 버그 수정")
    print("    docs: 문서     |  style: 포매팅")
    print("    refactor: 리팩토링  |  test: 테스트")


if __name__ == "__main__":
    print("━" * 33)
    print("  Week 11 Quiz - Easy 정답")
    print("━" * 33)
    problem1_solution()
    problem2_solution()
    problem3_solution()
    problem4_solution()
    print("\n" + "━" * 33)
