"""
Solutions - Medium Quiz (Week 7: Monocular Depth 이론)
"""


def main():
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("Week 7 Quiz - Medium 정답")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

    print("Q1. Teacher-Student 프레임워크:")
    print()
    print("  Step 1: Teacher 모델 학습")
    print("    - 라벨 있는 데이터 1.5M으로 DPT-Large 기반 Teacher 학습")
    print("    - 이 단계에서 Teacher는 높은 정확도를 가짐")
    print()
    print("  Step 2: 의사 라벨(Pseudo Label) 생성")
    print("    - 학습된 Teacher가 62M 비라벨 이미지에 대해 깊이맵 예측")
    print("    - 이 예측값이 Student 학습의 '의사 정답'이 됨")
    print()
    print("  Step 3: Student 모델 학습")
    print("    - 비라벨 62M (의사 라벨) + 라벨 1.5M (실제 라벨) 동시 학습")
    print("    - 강한 Data Augmentation 적용 (색상, 기하 변환 등)")
    print("    - ViT-S/B/L 다양한 크기로 학습")
    print()
    print("  Student > Teacher인 이유:")
    print("    1. 데이터 다양성: 62M의 다양한 장면으로 일반화 능력 극대화")
    print("    2. 강한 Augmentation: Teacher보다 더 어려운 조건에서 학습")
    print("       → 왜곡, 색상 변화 등에 강건해짐")
    print("    3. 지식 증류(Knowledge Distillation) 효과:")
    print("       Teacher의 '암묵적 지식'(soft label)이 전달됨")
    print("    4. Regularization 효과: 의사 라벨의 약간의 노이즈가")
    print("       오히려 과적합을 방지하는 역할\n")

    print("-" * 41)

    print("\nQ2. Scale-Invariant Loss:")
    print()
    print("  일반 L1 Loss로 혼합 학습 시 문제:")
    print("    L1 = |pred - gt|")
    print("    KITTI (0~80m): 오차 5m → L1 = 5.0")
    print("    NYU (0~10m): 오차 0.5m → L1 = 0.5")
    print("    → KITTI의 오차가 항상 크므로 NYU 학습이 무시됨!")
    print("    → 모델이 야외 데이터에 편향됨")
    print()
    print("  Scale-Invariant Loss 해결 방법:")
    print("    d_i = log(pred_i) - log(gt_i)")
    print("    L = (1/n) * sum(d_i^2) - (lambda/n^2) * (sum(d_i))^2")
    print()
    print("    핵심 동작:")
    print("    1. 로그 공간에서 계산 → 스케일 차이 완화")
    print("       log(80) - log(5) ≈ log(10) - log(0.6)")
    print("    2. 전체 평균 차이(shift)를 빼줌 → 이동 불변")
    print("    3. 결과: '상대적인 깊이 순서와 비율'만 학습")
    print("       → 스케일이 다른 데이터도 자연스럽게 혼합 가능!")
    print()
    print("    비유: '1등이 2등보다 2배 멀다'는 관계만 학습")
    print("          실제 거리가 80m든 10m든 상관없음\n")

    print("-" * 41)

    print("\nQ3. 깊이 추정과 SLAM의 관계:")
    print()
    print("  1. Scale Ambiguity (스케일 모호성):")
    print("     Monocular SLAM은 단일 카메라로 3D 복원을 하므로")
    print("     절대 스케일을 알 수 없음")
    print("     예: 실제 5m 이동을 했는데 SLAM은 '1 단위 이동'으로만 표현")
    print("     → 지도의 단위가 '미터'가 아닌 임의 단위")
    print()
    print("  2. Depth Anything의 상대 깊이를 SLAM에 활용하는 방법:")
    print("     a) Depth Prior: 초기 깊이 추정값으로 활용")
    print("        → Bundle Adjustment의 초기값 제공 → 수렴 속도 향상")
    print("     b) Scale 보정: 알려진 물체(사람 키 ~170cm)를 참조점으로")
    print("        상대 깊이 → 절대 깊이 변환 (d_metric = scale * d_rel + shift)")
    print("     c) Dense 초기화: 특징점 기반 SLAM의 sparse 깊이를")
    print("        dense 깊이맵으로 보완")
    print()
    print("  3. 깊이 추정 오차가 SLAM에 미치는 영향:")
    print("     - 3D 포인트 위치 오류 → 지도 왜곡")
    print("     - 스케일 드리프트 → 장기 주행 시 누적 오차")
    print("     - 루프 클로징 실패 → 잘못된 매칭")
    print("     - 특히 텍스처 없는 영역(벽, 하늘)에서 깊이 오차 큼")
    print()
    print("  4. 실제 시스템 권장 접근법:")
    print("     - 센서 융합: RGB 카메라 + IMU + (선택) RGB-D/LiDAR")
    print("     - Depth Prior로만 사용: GT 대신 초기 추정값으로 활용")
    print("     - 불확실성 기반: 깊이 추정의 신뢰도가 낮은 영역은")
    print("       SLAM에서 가중치를 낮춤")
    print("     - Known object 기반 스케일 보정 주기적 수행")

    print("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")


if __name__ == "__main__":
    main()
