"""
Phase 4.5 Week 4 - 검증 기준 + 변인 통제 퀴즈 정답
"""


def problem1_solution():
    print("\n" + "=" * 50)
    print("문제 1 해설: 층마다 배제하는 원인이 다르다")
    print("=" * 50 + "\n")
    print("답의 뼈대:")
    print("  1층 OOM 없이 적재      -> 용량 문제를 배제")
    print("  2층 VRAM baseline 일치 -> 양자화 미적용 / 부분 로드를 배제")
    print("  3층 출력 대역 검사     -> unnorm_key 오연결을 배제")
    print("  4층 결정성             -> 비결정 설정(do_sample, dropout) 잔존을 배제")
    print()
    print("  조용히 틀린 모델을 통과시키는 층은 3층이다.")
    print("  1·2·4층을 다 통과해도 옛 키로 역정규화되고 있으면 예외도 없고")
    print("  값도 그럴싸하며 결정적이다. 대역을 학습 통계와 대조하는 것만이")
    print("  그것을 잡는다.")
    print()
    print("  참고: 3층의 판정 근거는 두 곳에서 온다 --")
    print("  통계 파일의 분위수, 그리고 week1 실습 6 의 action 히스토그램.")


def problem2_solution():
    print("\n" + "=" * 50)
    print("문제 2 정답: B) 키가 실제로 적용되지 않았다")
    print("=" * 50 + "\n")
    print("해설:")
    print("  다른 로봇의 통계로 역정규화하면 스케일이 달라지므로 출력이 같을 수 없다.")
    print("  완전히 동일하다는 것은 두 호출이 같은 통계를 썼다는 뜻이다.")
    print()
    print("  확인할 것:")
    print("    - 주입한 구조가 모델이 읽는 형식과 같은가 (키 depth, 필드 이름)")
    print("    - 주입 위치가 모델이 실제로 참조하는 속성인가")
    print("    - predict_action 이 인자로 받은 키를 쓰는지, 아니면 설정값을 쓰는지")
    print()
    print("  A 가 틀린 이유: sim 렌더 데이터와 실로봇 데이터의 분위수가 우연히")
    print("  소수점 수준까지 같을 확률은 사실상 없다.")
    print("  D 가 틀린 이유: 정규화/역정규화는 학습으로 내재화되는 것이 아니라")
    print("  파이프라인 밖에서 통계로 수행되는 연산이다.")


def problem3_solution():
    print("\n" + "=" * 50)
    print("문제 3 해설: 14GB 는 양자화가 안 걸린 크기다")
    print("=" * 50 + "\n")
    print("답의 뼈대:")
    print("  (1) 의심: 양자화 설정이 적용되지 않아 fp16/bf16 으로 올라갔다.")
    print("      근거는 산수다 -- 7B x 2바이트 = 약 14-15GB 이고,")
    print("      4-bit 라면 약 4.4GB 대역이어야 한다. 14GB 는 정확히 비양자화 크기다.")
    print("      확인할 것: quantization_config 가 from_pretrained 에 전달됐는가,")
    print("      체크포인트 config 가 양자화 설정을 덮어쓰지 않는가.")
    print()
    print("      (OOM 이 안 난 것은 4070 12GB 기준으로는 오히려 이상하다 --")
    print("       메모리 측정 지점이나 device_map 분산 여부도 함께 본다)")
    print()
    print("  (2) 이 상태로 week5 를 진행하면 정밀도 조건이 zero-shot(4-bit)과")
    print("      달라진다. 성공률 차이에 양자화 차이가 섞여, before/after 를")
    print("      adaptation 효과로 해석할 수 없게 된다.")
    print("      즉 측정 자체가 무효가 되고 다시 재야 한다.")


def problem4_solution():
    print("\n" + "=" * 50)
    print("문제 4 정답: B) 기존 실측의 재현성이 깨진다")
    print("=" * 50 + "\n")
    print("해설:")
    print("  로컬 조합은 OpenVLA remote code 가 요구하는 범위로 고정돼 있고,")
    print("  그 위에서 Block 1-3 실측과 week0 baseline 이 측정됐다.")
    print("  버전을 올리면 그 측정들의 재현 근거가 사라진다.")
    print()
    print("  특히 week0 baseline 은 before/after 비교의 before 쪽이다.")
    print("  환경이 바뀌면 baseline 을 다시 재야 하고, 그러면 Section 3 일정에")
    print("  측정 하나가 추가된다.")
    print()
    print("  그래서 방향은 '로컬을 학습 환경에 맞춘다' 가 아니라")
    print("  '체크포인트가 로컬 조합에서 열리는지 확인한다' 다.")
    print("  안 열리면 두 선택지의 대가를 비교해 고르고, 고른 이유를 기록한다.")


def problem5_solution():
    print("\n" + "=" * 50)
    print("문제 5 해설: 바뀌는 것은 두 개뿐이다")
    print("=" * 50 + "\n")
    print("답의 뼈대:")
    print("  (1) 두 개다 -- 모델 경로와 unnorm_key.")
    print("      이 둘이 '모델을 바꾼다' 를 구성하는 최소 변경이다.")
    print()
    print("  (2) 고정 항목:")
    print("      - seed 목록 (week0 eval 전용 목록)")
    print("      - step cap")
    print("      - 카메라 키 경로 / 렌더 해상도 / 리사이즈 방식")
    print("      - instruction 문구")
    print("      - 4-bit 설정 (nf4 / double quant / compute dtype)")
    print("      - action 정변환 코드 (week0 계약 표 구현체)")
    print("      - 부분 도달률 판정식과 임계값")
    print("      - do_sample=False (결정성)")
    print()
    print("  (3) 고정이 깨지면 '동일 조건 N회 비교' 가 성립하지 않는다.")
    print("      그것이 Phase 4.5 의 성공 기준 문장 자체이므로,")
    print("      산출물의 주장이 무너진다 -- 성공률이 올랐든 안 올랐든.")


def problem6_solution():
    print("\n" + "=" * 50)
    print("문제 6 정답: B) 동작 기록만 하고 판단은 week5 로")
    print("=" * 50 + "\n")
    print("해설:")
    print("  1 episode 성공은 성공률에 대한 정보가 아니다. week0 에서 이미")
    print("  N=20 의 신뢰구간이 약 +-22%p 라고 적어 뒀다 -- N=1 은 말할 것도 없다.")
    print()
    print("  C 와 D 가 함정이다. 둘 다 '조금만 더 보자' 인데,")
    print("    C: 같은 seed 반복은 성공률이 아니다 (초기 배치가 같다)")
    print("    D: eval seed 를 미리 소진하거나, 통제되지 않은 조건으로 비교하게 된다")
    print("  그리고 어느 쪽이든 week5 의 해석에 선입견을 만든다.")
    print()
    print("  A 가 최악이다. 표본 1개로 결론을 내리고 측정을 줄이는 것은")
    print("  Phase 4.5 의 산출물(정량 분석) 자체를 포기하는 것이다.")


if __name__ == "__main__":
    print("=" * 50)
    problem1_solution()
    problem2_solution()
    problem3_solution()
    problem4_solution()
    problem5_solution()
    problem6_solution()
    print("=" * 50)
