"""
Phase 4.5 Week 0 - action 변환 계약 + 진단 논리 퀴즈 정답
"""


def problem1_solution():
    print("\n" + "=" * 50)
    print("문제 1 정답: C) action 변환 레이어")
    print("=" * 50 + "\n")
    print("해설:")
    print("  상한 대조가 18/20 이면 아래가 이미 배제된다:")
    print("    - env 설정 (control_mode, 카메라)")
    print("    - 루프 구조, step cap")
    print("    - 성공 판정")
    print()
    print("  그런데 기성 해법은 보통 변환 레이어를 우회해 제어 명령을 직접 만든다.")
    print("  따라서 상한 대조는 변환 레이어를 검증하지 못한다 -- 여기가 남는 용의자다.")
    print()
    print("  reached 조차 0 이라는 점이 단서다. 도메인 갭이라면 팔이 대상 근처로")
    print("  가려는 시도는 하는 편인데, 단위/부호가 틀리면 애초에 접근 자체가 없다.")
    print()
    print("  D 가 틀린 이유: 도메인 갭으로 결론 내려면 변환이 먼저 검증돼야 한다.")
    print("  검증 없이 '정상 결과' 로 기록하면 버그를 baseline 에 굳히게 된다.")


def problem2_solution():
    print("\n" + "=" * 50)
    print("문제 2 해설: 작은 델타에서 두 표현이 근사적으로 일치한다")
    print("=" * 50 + "\n")
    print("답의 뼈대:")
    print("  오일러각과 축-각(회전 벡터)은 회전량이 작을 때 서로 근사적으로 비슷하다.")
    print("  회전각이 0 에 가까우면 축 순서나 표현 차이가 만드는 오차도 같이 작아진다.")
    print()
    print("  VLA 의 한 스텝 델타는 원래 작다. 그래서 표현을 잘못 매핑해도")
    print("  움직임이 부드럽고 예외도 없다 -- '도는 것' 이 정합의 증거가 못 된다.")
    print()
    print("  누적되면 드러난다: 여러 스텝에 걸쳐 방향 오차가 쌓이면 자세가 서서히")
    print("  틀어지고, 파악 직전 정밀 자세 맞추기에서 실패한다.")
    print("  (증상이 '접근은 하는데 못 잡는다' 로 나타나면 이 계열을 의심한다)")
    print()
    print("  그래서 검증 수단이 필요하다: 표현·프레임을 계약 표로 출처와 함께 확정하고,")
    print("  공개 수치 대조로 변환까지 포함한 전체 경로를 맞춰 본다.")


def problem3_solution():
    print("\n" + "=" * 50)
    print("문제 3 정답: B) 훨씬 작게 움직여 거의 정지한 것처럼 보인다")
    print("=" * 50 + "\n")
    print("해설:")
    print("  action_space 가 [-1, 1] 이면 그 범위가 컨트롤러의 최대 델타에 대응한다.")
    print("  즉 1.0 이 '한 스텝 최대 이동', 0.01 은 '최대의 1%' 다.")
    print()
    print("  OpenVLA 의 un-normalize 된 값은 물리 단위(미터 대역)라 0.01 근처인데,")
    print("  이것을 정규화 값으로 해석하면 최대치의 1% 만 움직인다.")
    print("  -> 팔이 거의 안 움직이고, step cap 안에 아무 일도 일어나지 않는다.")
    print()
    print("  A 가 틀린 이유: 범위 안의 값이므로 예외는 나지 않는다. 조용히 틀린다.")
    print("  C 가 틀린 이유: 방향이 반대인 오류다 (정규화 값을 물리량으로 해석한 경우).")
    print()
    print("  교훈: '예외가 없다' 는 정합의 근거가 아니다. 두 규약을 문서가 아니라")
    print("  action_space 출력과 통계 출력으로 각각 확인해 표에 적어야 한다.")


def problem4_solution():
    print("\n" + "=" * 50)
    print("문제 4 해설: 차원별 정규화 적용 마스크")
    print("=" * 50 + "\n")
    print("답의 뼈대:")
    print("  (1) 역할: 7개 차원 중 어느 차원에 정규화/역정규화를 적용할지 표시한다.")
    print("      마스크가 꺼진 차원은 통계로 되돌리지 않고 값을 그대로 통과시킨다.")
    print()
    print("  (2) 마지막 차원이 다른 이유: gripper 는 연속적인 물리량이 아니라")
    print("      개폐 신호에 가깝다. 분위수로 스케일을 되돌리면 의미가 깨지므로")
    print("      다른 6개(위치 3 + 회전 3)와 같은 방식으로 다루지 않는다.")
    print()
    print("  (3) 놓치면 나오는 증상: gripper 값이 엉뚱한 스케일로 변환되어")
    print("      개폐 판정이 틀린다. 접근까지는 정상인데 물지 못하거나,")
    print("      집어야 할 때 펴는 동작이 나온다.")
    print()
    print("  계약 표의 5번 행(gripper 부호 규약)이 이것을 담는 자리다.")
    print("  ManiSkill 쪽의 개폐 부호 규약도 같은 행에 적어 둬야 대조가 된다.")


def problem5_solution():
    print("\n" + "=" * 50)
    print("문제 5 정답: C) 환경의 embodiment / 카메라 규약 정합을 손본다")
    print("=" * 50 + "\n")
    print("해설:")
    print("  A 가 틀린 이유가 핵심이다. 공개 벤치마크 기준으로 OpenVLA 의 sim 성적을")
    print("  가르는 변수는 task 난이도가 아니라 환경의 도메인 정합이다:")
    print("    - real2sim 정합 처리된 Google Robot 계열 -> 중간대 수치가 나온다")
    print("    - 정합 처리된 WidowX+Bridge 계열        -> 0% 근처")
    print("    - 정합 처리 없는 일반 sim task           -> 더 낮다")
    print()
    print("  즉 난이도를 낮춰도 OpenVLA 가 잘하는 구간으로 옮겨지지 않는다.")
    print("  손잡이는 (1) 환경의 embodiment/카메라 규약 정합, (2) 지표 해상도 두 개다.")
    print()
    print("  B, D 가 틀린 이유: N 이나 step cap 을 늘리는 것은 0 을 0 이 아니게")
    print("  만들지 못한다. 신호가 없는 원인은 표본 수나 시간이 아니다.")
    print()
    print("  주의: 정합을 높이면 'OpenVLA 미학습 분포' 요건과 충돌한다.")
    print("  embodiment/카메라 규약은 정합시키고 task/물체/씬은 신규로 두는 방향으로")
    print("  두 요건을 함께 판단한다 (Roadmap Section 0).")


def problem6_solution():
    print("\n" + "=" * 50)
    print("문제 6 해설: venv 를 합치지 않는 근거와 대안 구조")
    print("=" * 50 + "\n")
    print("답의 뼈대:")
    print("  (1) 근거: Measurements/openvla-rtx4070-int4/ 의 실측이 특정 버전 조합")
    print("      (transformers 4.40.1 / tokenizers 0.19.1 / timm 0.9.16 /")
    print("      accelerate 1.0.1 / bitsandbytes) 위에서 재현된다.")
    print("      OpenVLA remote code 가 이 범위를 벗어나면 경고 또는 즉시 중단이고,")
    print("      버전이 갈리면 Block 1-3 의 재현 근거가 사라진다.")
    print("      -> 증거의 재현성이 sim 편의보다 우선한다.")
    print()
    print("  (2) 대안 구조: 한 프로세스에서 못 쓰므로 두 프로세스로 나눈다.")
    print("      sim 프로세스가 관측 이미지를 내보내고, 추론 프로세스가 action 을")
    print("      돌려주는 형태 (파일 교환 또는 소켓).")
    print("      비용: 스텝마다 왕복이 생겨 episode 소요 시간이 늘어난다.")
    print("      단 sim 은 action 을 기다리므로 성공률에는 영향이 없다.")
    print()
    print("  어느 쪽을 택했든 판단과 근거를 outputs/env_decision.md 에 남긴다.")
    print("  이 결정은 Section 0 후반의 Docker 이미지 구성(단일 vs 다중)으로 이어진다.")


if __name__ == "__main__":
    print("=" * 50)
    problem1_solution()
    problem2_solution()
    problem3_solution()
    problem4_solution()
    problem5_solution()
    problem6_solution()
    print("=" * 50)
