"""
Solutions - Medium Quiz (Week 6: 성능 분석 및 개선)
"""


def main():
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("Week 6 Quiz - Medium 정답")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

    print("Q1. Ablation Study 해석:")
    print("    1) 가장 기여도가 높은 단일 기법: Multi-scale FPN (+1.5%)")
    print("       -> 다양한 크기의 객체에 대한 검출 능력을 향상시킴")
    print("       -> 특히 원거리(작은) 객체의 검출률이 크게 개선됨")
    print()
    print("    2) Multi-scale과 Augmentation의 시너지 효과:")
    print("       -> 개별 합: 1.5 + 1.3 = 2.8%p 향상 가능")
    print("       -> 실제 함께 사용: 2.7%p 향상")
    print("       -> 이는 두 기법이 일부 겹치는 효과가 있음을 의미")
    print("       -> 하지만 거의 가산적(additive)이므로 보완적 관계임")
    print()
    print("    3) 3D NMS 단독 효과가 작은 이유:")
    print("       -> NMS는 이미 검출된 결과의 후처리 단계")
    print("       -> 검출 자체의 품질(Depth 정확도)을 개선하지 않음")
    print("       -> 주로 Precision 향상에 기여하며, Recall에는 기여하지 않음")
    print("       -> Monocular에서는 중복 검출보다 미검출이 더 큰 문제\n")

    print("Q2. Depth 추정 개선 3가지 전략:")
    print("    전략 1 - Direct Regression:")
    print("      네트워크가 Depth 값(z)을 직접 회귀(regression)")
    print("      장점: 구현이 간단, end-to-end 학습 가능")
    print("      단점: 학습 데이터 분포에 의존, 원거리 정확도 낮음")
    print()
    print("    전략 2 - Depth Bin Classification:")
    print("      Depth를 구간(bin)으로 나눠 분류 + 잔차(offset) 회귀")
    print("      예: [0-5m, 5-10m, ..., 45-50m] 10개 bin")
    print("      장점: 분류 문제는 회귀보다 안정적, 이상치에 강건")
    print("      단점: bin 크기 설계에 민감, 연속적 예측이 아님")
    print()
    print("    전략 3 - 기하학적 제약 활용:")
    print("      차량 크기의 사전 지식과 2D bbox를 이용")
    print("      z = f * H_real / h_pixel (초점거리, 실제높이, 픽셀높이)")
    print("      장점: 물리적 의미가 있음, 학습 데이터 적어도 효과적")
    print("      단점: 정확한 클래스 분류 필요, 차량 크기 편차에 취약\n")

    print("Q3. 거리별 성능 진단:")
    print("    0-10m (AP3D 20.5% - 예상보다 낮음):")
    print("      주요 원인: Truncation (이미지 경계에서 잘림)")
    print("      가까운 객체는 이미지에서 크기가 커서 경계 밖으로 나감")
    print("      해결: Truncation 객체에 대한 보강 학습")
    print()
    print("    10-20m (AP3D 28.3% - 가장 좋은 구간):")
    print("      적절한 크기 + 적절한 거리 -> 시각적 단서 풍부")
    print()
    print("    20-30m (AP3D 12.1% - 급격한 성능 하락):")
    print("      주요 원인: Depth 오차 증가 (평균 ~3m)")
    print("      객체 크기가 줄어 시각적 단서 부족")
    print("      해결: Multi-scale feature, Depth 보조 Loss")
    print()
    print("    30-40m (AP3D 4.2% - 거의 실패):")
    print("      주요 원인: 심각한 Depth 오차 + 작은 객체 크기")
    print("      해결: 고해상도 feature map 사용, Depth prior 활용")
    print()
    print("    40m+ (AP3D 0.8% - 검출 불가):")
    print("      주요 원인: 매우 작은 객체, Depth 오차 5m+")
    print("      Monocular의 한계, Multi-view나 LiDAR fusion 필요")

    print("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")


if __name__ == "__main__":
    main()
