"""
Solutions - Medium Quiz (Week 8: Depth Anything 사용)
"""


def main():
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("Week 8 Quiz - Medium 정답")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

    print("Q1. Metric Depth 변환:")
    print()
    print("  연립방정식:")
    print("  1.5 = alpha * 0.85 + beta  ... (1)")
    print("  6.0 = alpha * 0.30 + beta  ... (2)")
    print()
    print("  (1) - (2):")
    print("  1.5 - 6.0 = alpha * (0.85 - 0.30)")
    print("  -4.5 = alpha * 0.55")
    print("  alpha = -4.5 / 0.55 = -8.182 (약 -8.18)")
    print()
    print("  beta = 1.5 - (-8.182) * 0.85 = 1.5 + 6.955 = 8.455 (약 8.45)")
    print()
    print("  정답: alpha = -8.18, beta = 8.45")
    print()
    print("  (참고: alpha가 음수인 이유는 상대 깊이에서 큰 값이 '가까움'이고")
    print("   절대 깊이에서 가까움은 '작은 값'이기 때문)")
    print()
    print("  상대 깊이 0.60인 픽셀:")
    print("  d_metric = -8.18 * 0.60 + 8.45 = -4.91 + 8.45 = 3.54m")
    print("  정답: 약 3.5m")
    print()
    print("  한계점:")
    print("  1. 선형 변환 가정: 실제 깊이-상대깊이 관계가 비선형일 수 있음")
    print("     → 특히 매우 가까운/먼 영역에서 오차 증가")
    print("  2. 참조점 의존: 참조점이 부정확하면 전체 변환이 틀어짐")
    print("     → 참조점의 깊이를 정확히 알아야 함")
    print("  3. 전역 스케일: 장면 전체에 하나의 선형 변환만 적용")
    print("     → 깊이에 따라 다른 스케일이 필요할 수 있음")
    print("  4. 장면 변화: 카메라 위치/각도가 바뀌면 보정 무효")
    print("     → 매번 새로 보정해야 할 수 있음")

    print("\n" + "-" * 41)

    print("\nQ2. 전처리 디버깅 - 잘못된 부분 4가지:")
    print()
    print("  버그 1: BGR → RGB 변환 누락")
    print("    OpenCV는 BGR 형식으로 이미지를 읽지만, 모델은 RGB를 기대")
    print("    수정: image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)")
    print()
    print("  버그 2: ImageNet 정규화 누락")
    print("    단순 /255.0은 [0,1] 범위만 맞춤. ImageNet mean/std 정규화 필요")
    print("    수정: AutoImageProcessor를 사용하면 자동 적용")
    print("      processor = AutoImageProcessor.from_pretrained(...)")
    print("      inputs = processor(images=image_pil, return_tensors='pt')")
    print()
    print("  버그 3: model.eval() 누락")
    print("    추론 시에는 eval() 모드로 전환해야 함")
    print("    (BatchNorm, Dropout 동작이 달라짐)")
    print("    수정: model.eval() 추가")
    print()
    print("  버그 4: torch.no_grad() 미사용")
    print("    추론 시 gradient 계산 불필요 (메모리 낭비)")
    print("    수정: with torch.no_grad(): output = model(**inputs)")
    print()
    print("  올바른 코드:")
    print("    from transformers import AutoModelForDepthEstimation, AutoImageProcessor")
    print("    from PIL import Image")
    print()
    print("    model = AutoModelForDepthEstimation.from_pretrained(...)")
    print("    model.eval()  # 추가!")
    print("    processor = AutoImageProcessor.from_pretrained(...)")
    print()
    print("    image_pil = Image.open('test.jpg')  # RGB 자동")
    print("    inputs = processor(images=image_pil, return_tensors='pt')")
    print()
    print("    with torch.no_grad():  # 추가!")
    print("        output = model(**inputs)")

    print("\n" + "-" * 41)

    print("\nQ3. YOLO + Depth 통합 전략:")
    print()
    print("  1. 깊이 값 요약 방법:")
    print("     min (최솟값)이 장애물 회피에 가장 적합")
    print()
    print("     이유:")
    print("     - mean: 배경이 포함되면 평균이 왜곡됨")
    print("       (사람 뒤의 먼 벽이 평균을 올림)")
    print("     - median: mean보다 낫지만 여전히 객체 경계에서 부정확")
    print("     - min: 객체에서 '가장 가까운 부분'의 깊이")
    print("       → 장애물 회피는 최악의 경우(가장 가까운 지점)를 기준으로 해야 함!")
    print("       → 안전 마진 확보")
    print()
    print("     실용적 보완:")
    print("     - 하위 10% percentile 사용 (노이즈 방지)")
    print("     - 바운딩 박스 중앙 70% 영역만 사용 (경계 제외)")
    print()
    print("  2. 장애물 우선순위 의사코드:")
    print("     obstacles = []")
    print("     for detection in yolo_detections:")
    print("         roi = depth_map[y1:y2, x1:x2]")
    print("         min_depth = percentile(roi, 10)  # 하위 10%")
    print("         obstacles.append((detection, min_depth))")
    print()
    print("     # 가까운 순으로 정렬 (깊이값 큰 것 = 가까움)")
    print("     obstacles.sort(key=lambda x: x[1], reverse=True)")
    print()
    print("     # 위험도 판단")
    print("     for obj, depth in obstacles:")
    print("         if depth > DANGER_THRESHOLD:    # 매우 가까움")
    print("             emergency_stop()")
    print("         elif depth > CAUTION_THRESHOLD:  # 주의")
    print("             slow_down()")
    print("         else:                            # 안전")
    print("             continue_navigation()")
    print()
    print("  3. Jetson 동시 실행 시 고려사항:")
    print("     메모리:")
    print("     - YOLO TensorRT FP16: ~200MB GPU")
    print("     - Depth TensorRT FP16: ~350MB GPU")
    print("     - 합계 ~550MB + 시스템 ~2GB = 총 ~2.5GB / 8GB")
    print("     → 여유 있음, 하지만 다른 프로세스와 경합 주의")
    print()
    print("     성능:")
    print("     - 두 모델을 순차 실행: YOLO(8ms) + Depth(50ms) = 58ms (~17FPS)")
    print("     - 병렬 실행 (CUDA Stream): 두 모델이 GPU 자원 경합")
    print("       → 순차보다 약간 빨라질 수 있지만 큰 차이 없음")
    print("     - 추천: 프레임 교대 실행 (짝수 프레임=YOLO, 홀수=Depth)")
    print("       또는 Depth는 2-3프레임마다 실행 (깊이 변화가 느리므로)")

    print("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")


if __name__ == "__main__":
    main()
